### PR TITLE
Added basic rest api test

### PR DESCRIPTION
**Pull request by cgole**

### CODE REVIEW

**Comment by superkhau** [comment]
This test is irrelevant for this example. If you want to test this example, please write a functional test that runs `slc loopback:boot-script` for both async and sync cases. The test should verify whether the files with the right contents were generated properly. See the README to understand the purpose of this example.

**Comment by cgole** [comment]
@superkhau, the intent of the story I have this sprint, is to add all examples to CI and to add some basic test to make sure that the test apps are up and running.  This will help catch failures which occur when there is a problem in the starting the loopback server itself. Functional tests are not within the scope of this story.

**Comment by superkhau** [comment]
In this example, you never start the server. However, I do see the intent of your story so if you would like to add a test to see if you could start the server, thats fine with me. The tests are failing though.

**Comment by superkhau** [comment]
LGTM, please merge after you get the tests to pass.

**Comment by cgole** [comment]
test please

**Comment by cgole** [comment]
test please

**Comment by cgole** [comment]
test please

**Pull request merged**
